name: $(Date:yyyyMMdd).$(Rev:r)
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/develop
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
trigger: none
pr: none
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    pool:
      name: 1ES_JavaTooling_Pool
      image: 1ES_JavaTooling_Windows_2022
      os: windows
    sdl:
      sourceAnalysisPool:
        name: 1ES_JavaTooling_Pool
        image: 1ES_JavaTooling_Windows_2022
        os: windows
      spotBugs:
        enabled: false
    customBuildTags:
      - MigrationTooling-mseng-VSJava-15024-Tool
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: Gradle-Build-Server-RC
            templateContext:
              outputs:
                - output: pipelineArtifact
                  artifactName: build-server
                  targetPath: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish Artifact: build-server"
            steps:
              - checkout: self
                clean: true
                fetchTags: false
              - task: JavaToolInstaller@0
                displayName: Use Java 17
                inputs:
                  versionSpec: "17"
                  jdkArchitectureOption: x64
                  jdkSourceOption: PreInstalled
              - task: Gradle@3
                displayName: gradlew build
                inputs:
                  publishJUnitResults: false
              - task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@2
                displayName: ESRP CodeSigning
                inputs:
                  ConnectedServiceName: vscjavaci_esrp_codesign
                  FolderPath: server/build/libs
                  Pattern: plugin.jar,server.jar
                  signConfigType: inlineSignParams
                  inlineOperation: |-
                    [
                      {
                        "KeyCode" : "CP-447347-Java",
                        "OperationCode" : "JavaSign",
                        "Parameters" : {
                            "SigAlg" : "SHA256withRSA",
                            "Timestamp" : "-tsa http://sha256timestamp.ws.digicert.com/sha256/timestamp"
                        },
                        "ToolName" : "sign",
                        "ToolVersion" : "1.0"
                      },
                      {
                        "KeyCode" : "CP-447347-Java",
                        "OperationCode" : "JavaVerify",
                        "Parameters" : {},
                        "ToolName" : "sign",
                        "ToolVersion" : "1.0"
                      }
                    ]
              ### Copy files for APIScan
              - task: CopyFiles@2
                displayName: "Copy Files for APIScan"
                inputs:
                  Contents: |-
                    server/build/libs/**/*.jar
                    server/build/libs/**/init.gradle
                  TargetFolder: $(Agent.TempDirectory)/APIScanFiles
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
              ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(Agent.TempDirectory)/APIScanFiles
                  softwareName: "gradle-build-server"
                  softwareVersionNum: "$(Build.BuildId)"
                  isLargeApp: false
                  toolVersion: "Latest"
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
              - task: CopyFiles@2
                displayName: Copy jars
                inputs:
                  Contents: |-
                    server/build/libs/**/*.jar
                    server/build/libs/**/init.gradle
                  TargetFolder: $(Build.ArtifactStagingDirectory)
